### ISSUE TITLE
feature: Grammar Support forthe  `#extension` Directive

### ISSUE THREAD

**Issue by Xaldew** [tree-sitter-grammars/tree-sitter-glsl#48]
### Did you check the tree-sitter docs?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

I was messing around a bit with the grammar to add 'official' support for the `#extension` preprocessor directive since I couldn't seem to modify the `preproc_call` rule to do the correct code high-lighting that I wanted:

![glsl_highlight](https://github.com/tree-sitter-grammars/tree-sitter-glsl/assets/1394310/f3c9a344-fe38-4458-95b9-0a4620004f63)

This is all implemented in this [fork](https://github.com/tree-sitter-grammars/tree-sitter-glsl/compare/master...Xaldew:tree-sitter-glsl:master) currently. I guess the question is, do you want me to open up a pull-request with this change, and if so is there anything else you want me to fix? I'm relatively new to the tree-sitter scene, so it's quite likely I've missed some details.

### Describe the solution you'd like

I essentially 'fixed' this by adding two new rules and appending them to the
`_top_level_items` and `_block_item` rules:

```
        _top_level_item: ($, original) => choice(
            ...original.members.filter((member) => member.content?.name != '_old_style_function_definition'),
            $.preproc_extension,
        ),

        _block_item: ($, original) => choice(
            ...original.members.filter((member) => member.content?.name != '_old_style_function_definition'),
            $.preproc_extension,
        ),

        preproc_extension: $ => seq(
          field('directive', $.preproc_directive),
          field('extension', $.identifier),
          token.immediate(/[ \t]*:[ \t]*/),
          field('behavior', $.extension_behavior),
          token.immediate(/\r?\n/),
        ),

        extension_behavior: $ => choice("require", "enable", "warn", "disable"),
```

### Describe alternatives you've considered

N/A

### Additional context

The official documentation for all GLSL preprocessor directives can be found here: https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.html#preprocessor

**Comment by theHamsta** [comment]
Thank you for your suggestion! I've merged it with you as co-author. Do you think the extension behavior should have a dedicated highlight for the new keywords?

**Comment by Xaldew** [comment]
Nice, thanks! I personally prefer to have a dedicated highlighting color as (both for enabled/disabled as shown in the screenshot), but it's hardly a hill I would die on :)
